package com.patient.demo.allergy;

import com.patient.demo.allergy.dto.AllergyCreateRequest;
import com.patient.demo.allergy.dto.AllergyResponse;
import com.patient.demo.allergy.dto.AllergyUpdateRequest;
import com.patient.demo.allergy.mapper.AllergyMapper;
import com.patient.demo.allergy.service.AllergyService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;

/**
 * Pure unit test for {@link AllergyService}: no Spring context, no database.
 *
 * <p>The repository is mocked because it is the boundary we want to cut. The mapper, in contrast,
 * is a <em>real</em> instance — it holds no collaborators and no I/O, so mocking it would only
 * hide bugs and force us to assert on interactions instead of on state.
 */
@ExtendWith(MockitoExtension.class)
class AllergyServiceTest {

    private static final UUID ID = UUID.fromString("11111111-1111-1111-1111-111111111111");

    @Mock
    private AllergyRepository repository;

    @Captor
    private ArgumentCaptor<Allergy> allergyCaptor;

    private AllergyService service;

    @BeforeEach
    void setUp() {
        service = new AllergyService(new AllergyMapper(), repository);
    }

    @Test
    @DisplayName("findAll maps every entity to a response and keeps the pagination metadata")
    void shouldMapPageContentAndPreserveMetadata() {
        Pageable pageable = PageRequest.of(0, 20);
        Page<Allergy> page = new PageImpl<>(List.of(allergy(ID, "Peanut")), pageable, 42);
        when(repository.findAll(pageable)).thenReturn(page);

        Page<AllergyResponse> result = service.findAll(pageable);

        assertThat(result.getContent()).singleElement()
                .satisfies(response -> {
                    assertThat(response.id()).isEqualTo(ID);
                    assertThat(response.name()).isEqualTo("Peanut");
                });
        assertThat(result.getTotalElements()).isEqualTo(42);
        assertThat(result.getNumber()).isZero();
        assertThat(result.getSize()).isEqualTo(20);
    }

    @Test
    @DisplayName("findById returns the mapped response when the row exists")
    void shouldReturnResponseWhenFound() {
        when(repository.findById(ID)).thenReturn(Optional.of(allergy(ID, "Latex")));

        AllergyResponse result = service.findById(ID);

        assertThat(result.id()).isEqualTo(ID);
        assertThat(result.name()).isEqualTo("Latex");
    }

    @Test
    @DisplayName("findById signals 404 when the row is missing")
    void shouldFailWithNotFoundOnMissingIdWhenReading() {
        when(repository.findById(ID)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.findById(ID))
                .isInstanceOf(ResponseStatusException.class)
                .extracting(exception -> ((ResponseStatusException) exception).getStatusCode())
                .isEqualTo(HttpStatus.NOT_FOUND);
    }

    @Test
    @DisplayName("save hands a new entity carrying the requested name to the repository")
    void shouldPersistNewEntity() {
        when(repository.save(any(Allergy.class))).thenAnswer(invocation -> invocation.getArgument(0));

        AllergyResponse result = service.save(createRequest("Penicillin"));

        verify(repository).save(allergyCaptor.capture());
        assertThat(allergyCaptor.getValue().getId()).as("id must be generated by the database").isNull();
        assertThat(allergyCaptor.getValue().getName()).isEqualTo("Penicillin");
        assertThat(result.name()).isEqualTo("Penicillin");
    }

    @Test
    @DisplayName("update mutates the managed entity and relies on dirty checking, not on save()")
    void shouldUpdateManagedEntityWithoutCallingSave() {
        Allergy managed = allergy(ID, "Aspirin");
        when(repository.findById(ID)).thenReturn(Optional.of(managed));

        AllergyResponse result = service.update(ID, updateRequest("Acetylsalicylic acid"));

        assertThat(managed.getName()).isEqualTo("Acetylsalicylic acid");
        assertThat(result.name()).isEqualTo("Acetylsalicylic acid");
        verify(repository, never()).save(any());
    }

    @Test
    @DisplayName("update signals 404 when the row is missing")
    void shouldFailWithNotFoundOnMissingIdWhenUpdating() {
        when(repository.findById(ID)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.update(ID, updateRequest("Anything")))
                .isInstanceOf(ResponseStatusException.class)
                .extracting(exception -> ((ResponseStatusException) exception).getStatusCode())
                .isEqualTo(HttpStatus.NOT_FOUND);
    }

    @Test
    @DisplayName("delete removes the row when it exists")
    void shouldDeleteExistingRow() {
        when(repository.existsById(ID)).thenReturn(true);

        service.delete(ID);

        verify(repository).existsById(ID);
        verify(repository).deleteById(ID);
        verifyNoMoreInteractions(repository);
    }

    @Test
    @DisplayName("delete signals 404 instead of silently doing nothing")
    void shouldFailWithNotFoundOnMissingIdWhenDeleting() {
        when(repository.existsById(ID)).thenReturn(false);

        assertThatThrownBy(() -> service.delete(ID))
                .isInstanceOf(ResponseStatusException.class)
                .extracting(exception -> ((ResponseStatusException) exception).getStatusCode())
                .isEqualTo(HttpStatus.NOT_FOUND);

        verify(repository, never()).deleteById(any());
    }

    private static Allergy allergy(UUID id, String name) {
        Allergy allergy = new Allergy();
        allergy.setId(id);
        allergy.setName(name);
        return allergy;
    }

    private static AllergyCreateRequest createRequest(String name) {
        return new AllergyCreateRequest(name);
    }

    private static AllergyUpdateRequest updateRequest(String name) {
        return new AllergyUpdateRequest(name);
    }
}


