package com.patient.demo.patient;

import com.patient.demo.patient.dto.PatientCreateRequest;
import com.patient.demo.patient.dto.PatientResponse;
import com.patient.demo.patient.dto.PatientUpdateRequest;
import com.patient.demo.patient.mapper.PatientMapper;
import com.patient.demo.patient.service.PatientService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Pure unit test for {@link PatientService}: repository mocked, mapper real.
 *
 * <p>The focus is the soft-delete contract — every read path must go through the
 * {@code ...AndIsDeletedFalse} finders, and {@code delete} must flip a flag rather than remove a
 * row.
 */
@ExtendWith(MockitoExtension.class)
class PatientServiceTest {

    private static final UUID ID = UUID.fromString("22222222-2222-2222-2222-222222222222");
    private static final LocalDate DOB = LocalDate.of(1990, 5, 17);

    @Mock
    private PatientRepository repository;

    @Captor
    private ArgumentCaptor<Patient> patientCaptor;

    private PatientService service;

    @BeforeEach
    void setUp() {
        service = new PatientService(repository, new PatientMapper());
    }

    @Test
    @DisplayName("findAll reads only the non-deleted rows and keeps the pagination metadata")
    void shouldListOnlyActivePatients() {
        // The page size must not exceed `total`, otherwise PageImpl recalculates the total itself.
        Pageable pageable = PageRequest.of(0, 1);
        Page<Patient> page = new PageImpl<>(List.of(patient(ID, "John", "Doe")), pageable, 7);
        when(repository.findAllByIsDeletedFalse(pageable)).thenReturn(page);

        Page<PatientResponse> result = service.findAll(pageable);

        assertThat(result.getContent()).singleElement()
                .satisfies(response -> {
                    assertThat(response.id()).isEqualTo(ID);
                    assertThat(response.firstName()).isEqualTo("John");
                    assertThat(response.lastName()).isEqualTo("Doe");
                    assertThat(response.dob()).isEqualTo(DOB);
                    assertThat(response.gender()).isEqualTo(Gender.MALE);
                });
        assertThat(result.getTotalElements()).isEqualTo(7);
    }

    @Test
    @DisplayName("findById returns the mapped response for an active patient")
    void shouldReturnActivePatient() {
        when(repository.findByIdAndIsDeletedFalse(ID)).thenReturn(Optional.of(patient(ID, "Jane", "Roe")));

        PatientResponse result = service.findById(ID);

        assertThat(result.id()).isEqualTo(ID);
        assertThat(result.firstName()).isEqualTo("Jane");
        assertThat(result.lastName()).isEqualTo("Roe");
    }

    @Test
    @DisplayName("findById signals 404 for a missing or already soft-deleted patient")
    void shouldFailWithNotFoundWhenReading() {
        when(repository.findByIdAndIsDeletedFalse(ID)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.findById(ID))
                .isInstanceOf(ResponseStatusException.class)
                .extracting(exception -> ((ResponseStatusException) exception).getStatusCode())
                .isEqualTo(HttpStatus.NOT_FOUND);
    }

    @Test
    @DisplayName("save hands a brand new, non-deleted entity to the repository")
    void shouldPersistNewPatient() {
        when(repository.save(any(Patient.class))).thenAnswer(invocation -> invocation.getArgument(0));

        PatientResponse result = service.save(new PatientCreateRequest("Ann", "Lee", "Marie", DOB, Gender.FEMALE));

        verify(repository).save(patientCaptor.capture());
        Patient saved = patientCaptor.getValue();
        assertThat(saved.getId()).as("id must be generated by the database").isNull();
        assertThat(saved.getFirstName()).isEqualTo("Ann");
        assertThat(saved.getLastName()).isEqualTo("Lee");
        assertThat(saved.getMiddleName()).isEqualTo("Marie");
        assertThat(saved.getDob()).isEqualTo(DOB);
        assertThat(saved.getGender()).isEqualTo(Gender.FEMALE);
        assertThat(saved.isDeleted()).as("a new patient is never created as deleted").isFalse();
        assertThat(result.firstName()).isEqualTo("Ann");
    }

    @Test
    @DisplayName("update mutates the managed entity, leaves isDeleted untouched and does not call save()")
    void shouldUpdateManagedPatientWithoutCallingSave() {
        Patient managed = patient(ID, "Old", "Name");
        when(repository.findByIdAndIsDeletedFalse(ID)).thenReturn(Optional.of(managed));

        PatientResponse result = service.update(ID,
                new PatientUpdateRequest("New", "Name", null, DOB, Gender.OTHER));

        assertThat(managed.getFirstName()).isEqualTo("New");
        assertThat(managed.getMiddleName()).isNull();
        assertThat(managed.getGender()).isEqualTo(Gender.OTHER);
        assertThat(managed.isDeleted()).as("update must never resurrect or delete a patient").isFalse();
        assertThat(result.firstName()).isEqualTo("New");
        verify(repository, never()).save(any());
    }

    @Test
    @DisplayName("update signals 404 for a missing or already soft-deleted patient")
    void shouldFailWithNotFoundWhenUpdating() {
        when(repository.findByIdAndIsDeletedFalse(ID)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.update(ID,
                new PatientUpdateRequest("A", "B", null, DOB, Gender.UNKNOWN)))
                .isInstanceOf(ResponseStatusException.class)
                .extracting(exception -> ((ResponseStatusException) exception).getStatusCode())
                .isEqualTo(HttpStatus.NOT_FOUND);
    }

    @Test
    @DisplayName("delete only raises the isDeleted flag — the row is never removed")
    void shouldSoftDeletePatient() {
        Patient managed = patient(ID, "Mark", "Twain");
        when(repository.findByIdAndIsDeletedFalse(ID)).thenReturn(Optional.of(managed));

        service.delete(ID);

        assertThat(managed.isDeleted()).isTrue();
        verify(repository, never()).delete(any());
        verify(repository, never()).deleteById(any());
    }

    @Test
    @DisplayName("delete signals 404 for a missing or already soft-deleted patient")
    void shouldFailWithNotFoundWhenDeleting() {
        when(repository.findByIdAndIsDeletedFalse(ID)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.delete(ID))
                .isInstanceOf(ResponseStatusException.class)
                .extracting(exception -> ((ResponseStatusException) exception).getStatusCode())
                .isEqualTo(HttpStatus.NOT_FOUND);
    }

    private static Patient patient(UUID id, String firstName, String lastName) {
        Patient patient = new Patient();
        patient.setId(id);
        patient.setFirstName(firstName);
        patient.setLastName(lastName);
        patient.setDob(DOB);
        patient.setGender(Gender.MALE);
        return patient;
    }
}


